[global]

# By default, Streamlit checks if the Python watchdog module is available and, if not,
# prints a warning asking for you to install it. The watchdog module is not required,
# but highly recommended. It improves the user experience by allowing you to automatically
# reload the app when its source code is changed. This config option allows you to
# suppress the warning if you prefer not to install watchdog.
disableWatchdogWarning = false

# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
showWarningOnDirectExecution = false

# DataFrame serialization.
# Legacy serialization format of st.dataframe and st.data_editor is deprecated
# and will be removed in a future version. Please use the new serialization format:
# https://docs.streamlit.io/library/advanced-features/configuration#toml
dataFrameSerialization = "legacy"

[logger]

# Level of logging: 'error', 'warning', 'info', or 'debug'.
level = "info"

[client]

# Whether to enable st.cache.
caching = true

# If false, makes your Streamlit script not draw to a Streamlit app.
displayEnabled = true

# Controls whether uncaught app exceptions are displayed in the browser. By default, this is set to True and Streamlit displays app exceptions and associated tracebacks in the browser.
showErrorDetails = true

[browser]

# Internet address where users should point their browsers in order to connect to the app. Can be IP address or DNS name and path.
serverAddress = "localhost"

# Port where users can connect to the app.
serverPort = 8501

# The base path for the URL where Streamlit should be reachable from.
baseUrlPath = ""

# Automatically open a browser window on startup?
gatherUsageStats = false

[server]

# List of folders that should not be watched for changes. This impacts both "Run on Save" and @st.cache.
folderWatchBlacklist = []

# Change the type of file watcher used by Streamlit, or turn it off completely.
fileWatcherType = "auto"

# Symmetric key used to produce signed cookies. If deploying on multiple replicas, this should be set to the same value across all replicas to ensure they all share the same secret.
cookieSecret = "a-random-key-here"

# If false, will attempt to open a browser window on start.
headless = false

# Automatically rerun script when the file is modified on disk.
runOnSave = false

# The address on which the server will listen for client and browser connections. Use this if you want to bind the server to a specific address. If set, the server will only be accessible from this address, and not from any other address.
address = "localhost"

# The port on which the server will listen for client and browser connections.
port = 8501

# Enables support for Cross-Origin Resource Sharing (CORS) for all origins. This is useful when you want to make HTTP requests to the Streamlit server from a web page served from a different domain.
enableCORS = false

# Enables support for Cross-Origin Resource Sharing (CORS) for WebSocket connections. This is useful when you want to make HTTP requests to the Streamlit server from a web page served from a different domain.
enableWebsocketCompression = false

[mapbox]

# Configure Streamlit to use a custom Mapbox token for elements like st.pydeck_chart and st.map.
token = ""
